# Generated by Django 5.0.6 on 2024-06-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annuaire", "0003_member_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="languagechoice",
            name="pt2b",
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
