# Generated by Django 5.0.6 on 2024-07-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annuaire", "0005_remove_member_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="display_email",
            field=models.BooleanField(
                default=False,
                verbose_name="J'accepte que mon adresse email soit publiée sur le site",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(
                error_messages={
                    "blank": "Veuillez renseigner ce champ",
                    "email": "Veuillez renseigner une adresse e-mail valide",
                    "unique": "Cet email est déjà enregistré dans l'annuaire",
                },
                max_length=254,
                unique=True,
                verbose_name="E-mail",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("F", "Femme"),
                    ("M", "Homme"),
                    ("X", "Aucun des genres ci-dessus"),
                ],
                help_text="Permettre d'afficher le genre sur les profils est un parti pris de l'équipe qui a développé l'annuaire. Cette démarche vise à favoriser la parité, en facilitant la recherche de profils féminins. ",
                max_length=100,
                verbose_name="Genre",
            ),
        ),
    ]
