# Generated by Django 5.0.9 on 2025-02-02 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annuaire", "0008_alter_member_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="pronouns",
            field=models.CharField(
                blank=True,
                help_text="Ce champ sera affiché après votre nom entre parenthèses si vous l'avez rempli. Exemple : Dominique Dupont (elle).",
                max_length=100,
                verbose_name="Pronoms",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="birth_year",
            field=models.IntegerField(
                error_messages={"blank": "Veuillez renseigner ce champ"},
                help_text="Votre année de naissance ne sera pas visible sur votre profil. Elle sera utilisée, uniquement, pour confirmer votre identité.",
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2025),
                ],
                verbose_name="Année de naissance",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Je ne souhaite pas répondre"),
                    ("F", "Femme"),
                    ("M", "Homme"),
                    ("X", "Aucun des genres ci-dessus"),
                ],
                default="",
                help_text="Ce champ n'apparaîtra pas sur votre page. Indiquer votre genre permet à l'annuaire de faciliter la recherche de profils féminins.",
                max_length=100,
                verbose_name="Genre",
            ),
        ),
    ]
