# Generated by Django 5.0.9 on 2026-03-26 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annuaire", "0009_member_pronouns_alter_member_birth_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="birth_year",
            field=models.IntegerField(
                error_messages={"blank": "Veuillez renseigner ce champ"},
                help_text="Votre année de naissance ne sera pas visible sur votre profil. Elle sera utilisée, uniquement, pour confirmer votre identité.",
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2026),
                ],
                verbose_name="Année de naissance",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="short_bio",
            field=models.CharField(
                error_messages={"blank": "Veuillez renseigner ce champ"},
                help_text='Exemple : "Je travaille à la collecte, l’indexation et l’analyse automatique de grands volumes de données."',
                max_length=200,
                verbose_name="Phrase de description",
            ),
        ),
    ]
