image: docker:stable

stages:
  - build_backend

variables:
  BACKEND_NAME: $CI_REGISTRY/scpomedialab/resin-annuaire-backend

before_script:
  - VERSION=$(echo $CI_COMMIT_TAG | sed -nre 's/^v([0-9.]+)$/\1/p')
  - if [ -n "${VERSION}" ]; then IMAGE_TAG=${VERSION}; else IMAGE_TAG=${CI_COMMIT_REF_SLUG}; fi

build_backend:
  stage: build_backend
  script:
    - docker build -t $BACKEND_NAME:$IMAGE_TAG -f Dockerfile .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker push $BACKEND_NAME:$IMAGE_TAG
  environment:
    name: $CI_COMMIT_REF_SLUG
  only:
    - tags